/** @type {import('tailwindcss').Config} */
module.exports = {
darkMode: 'class',
  content: [
    './app/**/*.{html,js,jsx,ts,tsx,mdx}',
    './components/**/*.{html,js,jsx,ts,tsx,mdx}',
    './utils/**/*.{html,js,jsx,ts,tsx,mdx}',
    './*.{html,js,jsx,ts,tsx,mdx}',
    './src/**/*.{html,js,jsx,ts,tsx,mdx}',
  ],
  presets: [require('nativewind/preset')],
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
    },
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#001caa',
          50: '#eff4ff',
          100: '#d3e4fe',
          200: '#bcc2ff',
          300: '#94a3b8',
          400: '#354be2',
          500: '#001caa',
          600: '#000c61',
          700: '#112ccb',
          800: '#1d35d1',
          900: '#0f172a',
          950: '#020617',
        },
        secondary: {
          DEFAULT: '#5b5e66',
          500: '#5b5e66',
        },
        tertiary: {
          DEFAULT: '#333640',
          500: '#333640',
        },
        error: {
          DEFAULT: '#ba1a1a',
          500: '#ba1a1a',
        },
        'primary-container': '#1d35d1',
        'on-primary': '#ffffff',
        'on-primary-container': '#b1b9ff',
        'inverse-primary': '#bcc2ff',
        'secondary-container': '#dfe2eb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#61646c',
        'tertiary-container': '#4a4d57',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#bbbeca',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f1f5f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444655',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#757687',
        'outline-variant': '#c5c5d8',
        'surface-tint': '#354be2',
        'primary-fixed': '#dfe0ff',
        'primary-fixed-dim': '#bcc2ff',
        'on-primary-fixed': '#000c61',
        'on-primary-fixed-variant': '#112ccb',
        'secondary-fixed': '#dfe2eb',
        'secondary-fixed-dim': '#c3c6cf',
        'on-secondary-fixed': '#181c22',
        'on-secondary-fixed-variant': '#43474e',
        'tertiary-fixed': '#e0e2ef',
        'tertiary-fixed-dim': '#c3c6d2',
        'on-tertiary-fixed': '#181b24',
        'on-tertiary-fixed-variant': '#434751',
        'surface-variant': '#d3e4fe',
        success: '#22c55e',
        warning: '#eab308',
      },
      fontFamily: {
        heading: undefined,
        body: undefined,
        mono: undefined,
        jakarta: ['var(--font-plus-jakarta-sans)'],
        roboto: ['var(--font-roboto)'],
        code: ['var(--font-source-code-pro)'],
        inter: ['var(--font-inter)'],
        'space-mono': ['var(--font-space-mono)'],
      },
      fontWeight: {
        extrablack: '950',
      },
      fontSize: {
        '2xs': '10px',
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'action-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }]
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        sm: '0.25rem',
        md: '0.75rem',
        'xl-2xl': '1.5rem',
      },
      spacing: {
        xl: '32px',
        lg: '24px',
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        'stack-lg': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'container-margin': '20px',
        'touch-target': '48px',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
};
